### ISSUE TITLE
Add support for reading Command text from a File

### ISSUE THREAD

**Issue by steveshortt** [SynapseProject/handlers.Sql.net#13]
Instead of hosting the command directly in the plan, read it from a file.

```yaml
- Name: ReadCommandFromFile
  Handler:
    Type: Synapse.Handlers.Sql:SqlServerHandler
    Config:
      Values:
        IntegratedSecurity: true
        Database: master
        DataSource: .\MSSQLLocalDB
  Parameters:
    Values:
      Text: c:\scripts\mycmd.sql
      IsFile: T | F  #something better than this...
      IsQuery: False
```
